lib/until_midnight_web/router.ex
defmodule UntilMidnightWeb.Router do
  use UntilMidnightWeb, :router

  import UntilMidnightWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {UntilMidnightWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", UntilMidnightWeb do
    pipe_through :browser

    live "/", PageLive, :index

    live "/:name", UserLive.Profile, :index

    live "/posts/:id", PostLive.Show
  end

  # Other scopes may use custom stacks.
  # scope "/api", UntilMidnightWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: UntilMidnightWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", UntilMidnightWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", UntilMidnightWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    live "/account/settings", UserLive.Settings
    live "/account/password", UserLive.PassSettings

    live "/:name/following", UserLive.Profile, :following
    live "/:name/followers", UserLive.Profile, :followers

    live "/post/new", PostLive.New
  end

  scope "/", UntilMidnightWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/until_midnight_web/controllers/user_session_controller.ex
defmodule UntilMidnightWeb.UserSessionController do
  use UntilMidnightWeb, :controller

  alias UntilMidnight.Accounts
  alias UntilMidnightWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      UserAuth.log_in_user(conn, user, user_params)
    else
      # In order to prevent user enumeration attacks, don't disclose whether the email is registered.
      render(conn, "new.html", error_message: "Invalid email or password")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.log_out_user()
  end
end

lib/until_midnight_web/views/user_session_view.ex
defmodule UntilMidnightWeb.UserSessionView do
  use UntilMidnightWeb, :view
end

lib/until_midnight_web/templates/user_session/new.html.heex
<h1 class="text-white">Unt Midnight Social</h1>
<p class="text-white">Sign In to connect on social network.</p>

<.form let={f} for={@conn} action={Routes.user_session_path(@conn, :create)} as={:user}>
  <%= if @error_message do %>
    <p class="text-white"><%= @error_message %></p>
  <% end %>

  <%= label f, :email, class: "text-white" %>
  <%= email_input f, :email, required: true %>
  <%= error_tag f, :email, class: "text-white" %>

  <%= label f, :password, class: "text-white" %>
  <%= password_input f, :password, required: true %>
  <%= error_tag f, :password, class: "text-white" %>

  <%= label f, :remember_me, "Keep me logged in for 60 days", class: "text-white" %>
  <%= checkbox f, :remember_me %>

  <%= submit "Sign In",  phx_disable_with: "Sign in.....", class: "text-white" %>
</.form>

<p>
  <%= link "SignUp", to: Routes.user_registration_path(@conn, :new), class: "text-white" %> |
  <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new), class: "text-white" %>
</p>